djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('spytnik.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spytnik/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('info/', views.InfoView.as_view(), name="info"),
    path('user/<username>', views.ProfileView.as_view(), name="profile"),
    path('offtop', views.PostListView.as_view(), name="other"),
    path('movies', views.PostListView.as_view(), name="movies"),
    path('music', views.PostListView.as_view(), name="music"),
    path('life', views.PostListView.as_view(), name="life"),
    path('<slug:slug>/', views.PostListView.as_view(), name="posts"),
    path('<slug:slug>/<slug:title_slug>', views.TitleView.as_view(), name="title"),


]

spytnik/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Genre(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(max_length=20, null=True)

    def __str__(self):
        return self.name


class Pleb(models.Model):
    user = models.OneToOneField(User, unique=True, on_delete=models.CASCADE)


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='articles/', null=True)
    genre = models.ManyToManyField(Genre)
    isChosen = models.BooleanField(default=False,null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    slug = models.SlugField(max_length=25, default='')
    published_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("title", kwargs={"slug": self.genre.first().slug, "title_slug": self.slug})


class PostDescription(models.Model):
    image = models.ImageField(upload_to='articles/', null=True)
    text = models.TextField(null=True)
    belong = models.ForeignKey(Post, related_name="description", on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.text


class Vote(models.Model):
    value = models.SmallIntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    voted_date = models.DateTimeField(auto_now_add=True)

spytnik/views.py
import json
from datetime import datetime
from pprint import pprint

from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, TemplateView
from spytnik.models import Post
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from . models import Pleb, Vote, Genre


class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(genre__slug=self.kwargs.get("slug"))


    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)

        slug = self.request.path
        slug = slug[1:]

        tags = Genre.objects.all()
        for tag in tags:
            if tag.slug == slug:
                context['tag'] = tag.name
                t = tag
        return context


class InfoView(ListView):
    template_name = 'spytnik/info.html'

    def get_queryset(self):
        return Post.objects.filter(isChosen=True).select_related()


class ProfileView(ListView):
    model = Vote
    template_name = 'spytnik/account.html'
    success_url = reverse_lazy('home')

    def get_queryset(self):
        return Vote.objects.filter(user=self.request.user).select_related()

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)

        votes = Vote.objects.filter(user=self.request.user).select_related()
        count = votes.count()
        sum = 0
        for vot in votes:
            sum += vot.value
        if count > 0:
            context['average'] = sum/count
        else:
            context['average'] = "--"
        return context

    def post(self, request, *args, **kwargs):
        print(request.POST.get("submit"))
        if request.POST.get("submit"):
            logout(request)
            next = request.POST.get('next', '/')
            return HttpResponseRedirect(next)


class TitleView(DetailView):
    model = Post
    slug_url_kwarg = 'title_slug'
    context_object_name = "post"
    template_name = "spytnik/title.html"

    def get_context_data(self, **kwargs):
        context = super(DetailView, self).get_context_data(**kwargs)
        item = kwargs.get('object')
        votes = Vote.objects.filter(post__slug=item.slug).select_related()
        if votes.count() > 0:
            sum = 0
            for vot in votes:
                sum += vot.value
            context['average'] = sum/votes.count()
        else:
            context['average'] = '--'
        return context

    def post(self, request, *args, **kwargs):
        value = 0
        if request.POST.get('submit') == 's_1':
            value = 1
        elif request.POST.get('submit') == 's_2':
            value = 2
        elif request.POST.get('submit') == 's_3':
            value = 3
        elif request.POST.get('submit') == 's_4':
            value = 4
        elif request.POST.get('submit') == 's_5':
            value = 5

        current = Post.objects.filter(slug=self.kwargs['title_slug']).select_related().first()
        t = Vote.objects.all().filter(user=self.request.user, post=current)
        print(t)
        if t.count() > 0:
            temp = t.first()
            print(temp.voted_date)
            temp.value = value
            temp.voted_date = datetime.now()
            temp.save()
        else:
            vote = Vote(value=value, user=self.request.user, post=current, voted_date=datetime.now())
            vote.save()
        next = request.POST.get('next', '/')
        return HttpResponseRedirect(next)


class HomeView(ListView):
    model = Post
    paginate_by = 12
    template_name = "spytnik/index.html"

    def post(self, request):
        print(request.POST)
        if request.POST.get("reg_username") is None:
            name = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(request, username=name, password=password)
            if user:
                login(request, user)
                return JsonResponse(data={'url': 'user/' + name}, status=201)
            return JsonResponse(data={'error': "Неверное емя пользователя или пароль"}, status=400)
        else:
            name = request.POST.get("reg_username")
            pass1 = request.POST.get("reg_pass1")
            user = User.objects.create_user(username=name, password=pass1)
            print(user)
            if user:
                user.save()
                plebs = Pleb(user=user)
                plebs.save()
                login(request, user)
                return JsonResponse(data={'url': 'user/' + name}, status=201)
            return JsonResponse(data={'error': "Данное имя пользователя уже используется"}, status=400)

spytnik/templates/pages/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../styles/styles.css">
    <link rel="stylesheet" href="../styles/icons.css">
    <link rel="stylesheet" type="text/css" href="../js/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="../js/slick/slick-theme.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Title</title>
</head>

<body>
<div class="background">
    <div class="stick"><img src="../Resources/sur.jpg"></div>
</div>
<header>
    <div class="header-container">
        <ul class="menu-header_list">
            <li class="menu-header_item"><a class="item" href="#">Статьи
                <span class="arrow"></span></a>
                <div class="sub_menu">
                    <ul class="submenu">
                        <li class="sub_item"><a class="item" href="#">оффтоп</a></li>
                        <li class="sub_item"><a class="item" href="#">лучшее</a></li>
                        <li class="sub_item"><a class="item" href="#">музыка</a></li>
                        <li class="sub_item"><a class="item" href="#">жизнб</a></li>
                    </ul>
                </div>
            </li>
            <li class="menu-header_item logo_item"><a class="logo icon-satellite" href="index.html"></a></li>
            <li class="menu-header_item"><a class="item" href="info.html">Издательство</a></li>
        </ul>
    </div>
    <div class="nav">
        <a class="account_logo" href="#popup"><i class="fa fa-user-circle" aria-hidden="true"></i></a>
    </div>
</header>

<main id="mn">
    <div class="slider">
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>

        <div class="slider_item">
            <div class="picture" style="background-image: url('../Resources/int.jpg')"></div>
            <div class="title">авашот</div>
        </div>
        <div class="slider_item">
            <div class="picture" style="background-image: url('../Resources/int.jpg')"></div>
            <div class="title">авашот</div>
        </div>
    </div>
    <div class="wrapper">
        <div class="content_wrapper">
            <div class="page">
                <div class="page_title"><span>исскуство быть</span></div>
                <div class="page_info">
                    <div class="author"><a class="author_ref" href="#">бутома</a></div>
                    <div class="tag"><a class="tag_ref" href="#">#жизнб</a></div>
                    <div class="date">20.05.22</div>
                </div>
                <a class="cover" href="#"><img src="../Resources/grf.jpg"></a>
            </div>
        </div>
        <div class="content_wrapper">
            <div class="page">
                <div class="page_title"><span>исскуство быть</span></div>
                <div class="page_info">
                    <div class="author"><a class="author_ref" href="#">бутома</a></div>
                    <div class="tag"><a class="tag_ref" href="#">#жизнб</a></div>
                    <div class="date">20.05.22</div>
                </div>
                <div class="cover"><img src="../Resources/grf.jpg"></div>
            </div>
        </div>
        <div class="content_wrapper">
            <div class="page">
                <div class="page_title"><span>исскуство быть </span></div>
                <div class="page_info">
                    <div class="author"><a class="author_ref" href="#">бутома</a></div>
                    <div class="tag"><a class="tag_ref" href="#">#жизнб</a></div>
                    <div class="date">20.05.22</div>
                </div>
                <div class="cover"><img src="../Resources/grf.jpg"></div>
            </div>
        </div>
        <div class="content_wrapper">
            <div class="page">
                <div class="page_title"><span>исскуство быть</span></div>
                <div class="page_info">
                    <div class="author"><a class="author_ref" href="#">бутома</a></div>
                    <div class="tag"><a class="tag_ref" href="#">#жизнб</a></div>
                    <div class="date">20.05.22</div>
                </div>
                <a class="cover" href="#"><img src="../Resources/grf.jpg"></a>
            </div>
        </div>
        <div class="content_wrapper">
            <div class="page">
                <div class="page_title"><span>исскуство быть</span></div>
                <div class="page_info">
                    <div class="author"><a class="author_ref" href="#">бутома</a></div>
                    <div class="tag"><a class="tag_ref" href="#">#жизнб</a></div>
                    <div class="date">20.05.22</div>
                </div>
                <a class="cover" href="#"><img src="../Resources/grf.jpg"></a>
            </div>
        </div>
        <div class="content_wrapper">
            <div class="page">
                <div class="page_title"><span>исскуство быть</span></div>
                <div class="page_info">
                    <div class="author"><a class="author_ref" href="#">бутома</a></div>
                    <div class="tag"><a class="tag_ref" href="#">#жизнб</a></div>
                    <div class="date">20.05.22</div>
                </div>
                <a class="cover" href="#"><img src="../Resources/grf.jpg"></a>
            </div>
        </div>
        <div class="content_wrapper">
            <div class="page">
                <div class="page_title"><span>исскуство быть </span></div>
                <div class="page_info">
                    <div class="author"><a class="author_ref" href="#">бутома</a></div>
                    <div class="tag"><a class="tag_ref" href="#">#жизнб</a></div>
                    <div class="date">20.05.22</div>
                </div>
                <div class="cover"><img src="../Resources/grf.jpg"></div>
            </div>
        </div>
    </div>
    <footer>
        <div class="page_end">
            <p>© 2022 Спутник</p>
        </div>
        <div class="links">
            <a href="https://github.com/qwSlane"><i class="fa fa-github" aria-hidden="true"></i></a>
        </div>
    </footer>
</main>

<div id="popup" class="popup">
    <div class="popup_body">
        <a href="#head" class="popup_area"></a>
        <div class="container">
            <div class="popup_content">
                <div class="front" id="front_">
                    <div class="popup_title">ВХОД</div>
                    <div class="icon"><span class="fa fa-user-o" aria-hidden="true"></span></div>
                    <form class="login_form">
                        <div class="form_group"><input type="text" class="form_control" placeholder="Имя пользователя"
                                                       required/></div>
                        <div class="form_group"><input type="text" class="form_control" placeholder="Пароль" required>
                        </div>
                        <div class="form_group">
                            <div class="reg reg-1" id="elem">Регистрация</div>
                        </div>
                        <div class="form_group">
                            <button class="btn submit">Войти</button>
                        </div>
                    </form>
                </div>
                <div class="back" id="back_">
                    <div class="popup_title">РЕГИСТРАЦИЯ</div>
                    <div class="icon"><span class="fa fa-user-o" aria-hidden="true"></span></div>
                    <form class="login_form">
                        <div class="form_group"><input type="text" class="form_control" placeholder="Имя пользователя"
                                                       required/></div>
                        <div class="form_group"><input type="text" class="form_control" placeholder="Пароль" required>
                        </div>
                        <div class="form_group">
                            <div class="reg" id="elem-1">Вход</div>
                        </div>
                        <div class="form_group">
                            <button class="btn submit">Регистрация</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- <div class="search-bar">
     <form action="" method="get">
         <input name="s" placeholder="Search..." type="search" spellcheck="false">
         <button type="submit"></button>
     </form>
 </div> -->
<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="../js/slick/slick.min.js"></script>
<script src="../js/script.js"></script>
</body>
</html>

spytnik/templates/pages/info.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="../styles/styles.css">
    <link rel="stylesheet" href="../styles/info.css">
    <link rel="stylesheet" href="../styles/icons.css">
    <link rel="stylesheet" type="text/css" href="../js/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="../js/slick/slick-theme.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Title</title>
</head>

<body>
<div class="background">
    <div class="stick"><img src="../Resources/sur.jpg"></div>
</div>
<header>
    <div class="header-container">
        <ul class="menu-header_list">
            <li class="menu-header_item"><a class="item" href="#">Статьи
                <span class="arrow"></span></a>
                <div class="sub_menu">
                    <ul class="submenu">
                        <li class="sub_item"><a class="item" href="#">оффтоп</a></li>
                        <li class="sub_item"><a class="item" href="#">лучшее</a></li>
                        <li class="sub_item"><a class="item" href="#">музыка</a></li>
                        <li class="sub_item"><a class="item" href="#">жизнб</a></li>
                    </ul>
                </div>
            </li>
            <li class="menu-header_item logo_item"><a class="logo icon-satellite" href="index.html"></a></li>
            <li class="menu-header_item"><a class="item" href="info.html">Издательство</a></li>
        </ul>
    </div>
    <div class="nav">
        <a class="account_logo" href="#popup"><i class="fa fa-user-circle" aria-hidden="true"></i></a>
    </div>
</header>
<main id="mn">
    <div class="slider">
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>
        <div class="slider_item">
            <a class="topic" href="#">
                <div class="picture" style="background-image: url('../Resources/int.jpg')">
                    <div class="title"><span>example, ex</span></div>
                </div>
            </a>
        </div>

        <div class="slider_item">
            <div class="picture" style="background-image: url('../Resources/int.jpg')"></div>
            <div class="title">авашот</div>
        </div>
        <div class="slider_item">
            <div class="picture" style="background-image: url('../Resources/int.jpg')"></div>
            <div class="title">авашот</div>
        </div>
    </div>
    <div class="information">
        <div class="info_title"><h1> ОБ ИЗДАТЕЛЬСТВЕ</h1></div>
        <div class="description">
            <div class="center_content">
                <p>
                    «Спутник» — регулярное издательство, основанное в 2022 году. Ресурс публикует преимущественно
                    публицистику и художественную литературу. В публицистике преобладает эссеистика, true story,
                    психоанализ и философия. </p>
                <p><strong>Главный редактор:</strong> ФИФТИСЭНТ
                    <br>
                    <strong>По общим вопросам: </strong><a href="https://t.me/deqq0">deqq0</a>
                </p>
            </div>
        </div>
    </div>
    <footer>
    <div class="page_end">
        <p>© 2022 Спутник</p>
    </div>
    <div class="links">
        <a href="https://github.com/qwSlane"><i class="fa fa-github" aria-hidden="true"></i></a>
    </div>
</footer>
</main>
<div id="popup" class="popup">
    <div class="popup_body">
        <a href="#head" class="popup_area"></a>
        <div class="container">
            <div class="popup_content">
                <div class="front" id="front_">
                    <div class="popup_title">ВХОД</div>
                    <div class="icon"><span class="fa fa-user-o" aria-hidden="true"></span></div>
                    <form class="login_form">
                        <div class="form_group"><input type="text" class="form_control" placeholder="Имя пользователя"
                                                       required/></div>
                        <div class="form_group"><input type="text" class="form_control" placeholder="Пароль" required>
                        </div>
                        <div class="form_group">
                            <div class="reg reg-1" id="elem">Регистрация</div>
                        </div>
                        <div class="form_group">
                            <button class="btn submit">Войти</button>
                        </div>
                    </form>
                </div>
                <div class="back" id="back_">
                    <div class="popup_title">РЕГИСТРАЦИЯ</div>
                    <div class="icon"><span class="fa fa-user-o" aria-hidden="true"></span></div>
                    <form class="login_form">
                        <div class="form_group"><input type="text" class="form_control" placeholder="Имя пользователя"
                                                       required/></div>
                        <div class="form_group"><input type="text" class="form_control" placeholder="Пароль" required>
                        </div>
                        <div class="form_group">
                            <div class="reg" id="elem-1">Вход</div>
                        </div>
                        <div class="form_group">
                            <button class="btn submit">Регистрация</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="https://code.jquery.com/jquery-2.2.0.min.js" type="text/javascript"></script>
<script type="text/javascript" src="../js/slick/slick.min.js"></script>
<script src="../js/script.js"></script>
</body>
</html>

templates/pages/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/spytnik/account.html
{% extends 'base.html' %}

{% block content %}
    <main>
        <div class="user_info">
            <div class="info">
                <div class="info_icon">
                    {% if user.is_authenticated %}
                        <form class="" method="POST" action="{% url 'profile' user.username %}">
                            {% csrf_token %}
                            <button type="submit" name="submit" value="logout" class="btn">Выход</button>
                        </form>
                    {% endif %}
                    <span class="fa fa-user-o" aria-hidden="true"></span></div>
                <div class="text_info">
                    <div class="user_nickname"><h3>{{ user.username }}</h3></div>
                    <div class="stats">
                        <div class="user_role">
                            <div class="user_tag">РОЛЬ</div>
                            <h4>ПОЛЬЗОВАТЕЛЬ</h4>
                        </div>
                        <div class="rating">
                            <div class="user_tag">РЕЙТИНГ</div>
                            <h4>{{ average }}</h4>
                        </div>
                        <div class="registration_date">
                            <div class="user_tag">ДАТА РЕГИСТРАЦИИ</div>
                            <h4>{{ user.date_joined }}</h4></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="table">
            <div class="info_title"><h1> ИСТОРИЯ ОЦЕНОК</h1></div>

            <div class="board">
                <div class="board_head">
                    <div class="column num">№</div>
                    <div class="column name">статья</div>
                    <div class="column date_time">дата и время</div>
                    <div class="space"></div>
                    <div class="column vote">оценка</div>
                </div>
                 {% for vote in vote_list %}
                <div class="board_item">
                    <div class="column num">1</div>
                    <div class="column name"><a href="{{ vote.post.get_absolute_url }}">{{ vote.post.title }}</a></div>
                    <div class="date_time">{{ vote.voted_date }}</div>
                    <div class="space"></div>
                    <div class="vote">{{ vote.value }}</div>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>
{% endblock content %}

templates/spytnik/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="slider">
        {% for post in post_list %}
            {% if post.isChosen %}
            <div class="slider_item">
                <a class="topic" href="{{ post.get_absolute_url }}">
                    <div class="picture" style="background-image: url('{{ post.image.url }}')">
                        <div class="title"><span>{{ post.title }}</span></div>
                    </div>
                </a>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    <div class="wrapper">
        {% for post in post_list %}
            <div class="content_wrapper">
                <div class="page">
                    <div class="page_title"><span>{{ post.title }}</span></div>
                    <div class="page_info">
                        <div class="author"><a class="author_ref" href="#">{{ post.author }}</a></div>
                        <div class="tag">
                            {% for tag in post.genre.all %}
                                <a class="tag_ref" href="">#{{ tag.name }}</a></div>
                            {% endfor %}
                        <div class="date">{{ post.published_date }}</div>
                    </div>
                    <a class="cover" href="{{ post.get_absolute_url }}"><img src="{{ post.image.url }}"></a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock content %}

templates/spytnik/info.html
{% extends 'base.html' %}

{% load static %}
<link rel="stylesheet" href="{% static 'styles/info.css' %}">
{% block content %}
<main id="mn">
    <div class="slider">
      {% for post in post_list %}
            <div class="slider_item">
                <a class="topic" href="{{ post.get_absolute_url }}">
                    <div class="picture" style="background-image: url('{{ post.image.url }}')">
                        <div class="title"><span>{{ post.title }}</span></div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <div class="information">
        <div class="info_title"><h1> ОБ ИЗДАТЕЛЬСТВЕ</h1></div>
        <div class="description">
            <div class="center_content">
                <p>
                    «Спутник» — регулярное издательство, основанное в 2022 году. Ресурс публикует преимущественно
                    публицистику и художественную литературу. В публицистике преобладает эссеистика, true story,
                    психоанализ и философия. </p>
                <p><strong>Главный редактор:</strong> ФИФТИСЭНТ
                    <br>
                    <strong>По общим вопросам: </strong><a href="https://t.me/deqq0">deqq0</a>
                </p>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

templates/spytnik/post_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="slider">
         {% for post in post_list %}
            <div class="slider_item">
                <a class="topic" href="{{ post.get_absolute_url }}">
                    <div class="picture" style="background-image: url('{{ post.image.url }}')">
                        <div class="title"><span>{{ post.title }}</span></div>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <div class="wrapper">
        <div class="ititle">
            <h1>Категория:{{ tag }} </h1>
        </div>
            {% for post in post_list %}
                {% if post_list.count > 0  %}
                <div class="content_wrapper">
                    <div class="page">
                        <div class="page_title"><span>{{ post.title }}</span></div>
                        <div class="page_info">
                            <div class="author"><a class="author_ref" href="#">{{ post.author }}</a></div>
                            <div class="tag">
                                {% for tag in post.genre.all %}
                                    <a class="tag_ref" href="{% url tag.slug %} "> #{{ tag.name }}</a></div>
                                {% endfor %}
                            <div class="date">{{ post.published_date }}</div>
                        </div>
                        <a class="cover" href="{{ post.get.url }}"><img src="{{ post.image.url }}"></a>
                    </div>
                </div>
                 {% endif %}
            {% endfor %}
    </div>
{% endblock content %}